name: eticon_struct
description: Package for creating the project structure and individual elements. Will help you create the necessary elements in one line!
version: 1.0.1
homepage: https://github.com/kensamare/eticon_structure

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  args: ^2.3.0
  dart_style: ^2.2.0
  eticon_api: ^1.3.2
  flutter:
    sdk: flutter
  process_run: ^0.12.2+2
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

