name: eticon_struct
description: A new Flutter project.
version: 1.0.0-pre
homepage: https://github.com/kensamare/eticon_structure

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  args: ^2.3.0
  flutter:
    sdk: flutter
  process_run: ^0.12.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

